allow_remote_control yes
listen_on unix:/tmp/kitty

# enabled_layouts tall,fat,stack
enabled_layouts tall,stack

map ctrl+shift+enter new_window_with_cwd

# map ctrl+shift+/ show_scrollback

# map ctrl+shift+h neighboring_window left
# map ctrl+shift+l neighboring_window right
# map ctrl+shift+k neighboring_window up
# map ctrl+shift+j neighboring_window down
# # map alt+h neighboring_window left
# # map alt+l neighboring_window right
# # map alt+k neighboring_window up
# # map alt+j neighboring_window down

map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right
map --when-focus-on var:IS_VIM=true alt+h
map --when-focus-on var:IS_VIM=true alt+j
map --when-focus-on var:IS_VIM=true alt+k
map --when-focus-on var:IS_VIM=true alt+l

map alt+shift+h move_window left
map alt+shift+j move_window down
map alt+shift+k move_window up
map alt+shift+l move_window right

map ctrl+shift+, previous_tab
# map ctrl+shift+, kitten tab_no_cycle.py next
# map ctrl+shift+, kitten @ goto-tab -1
map ctrl+shift+. next_tab
# map ctrl+shift+, kitten tab_no_cycle.py prev
# map ctrl+shift+. kitten @ goto-tab +1
map ctrl+shift+left move_tab_backward
map ctrl+shift+right move_tab_forward

map ctrl+shift+alt+. detach_window tab-right
map ctrl+shift+alt+, detach_window tab-left

# tab_bar_min_tabs 1

remember_window_size no
# initial_window_width 800
# initial_window_height 400

# when there is only a single window, no margin or border
single_window_margin_width 0
single_window_padding_width 0

# when there is multiple windows, add a small margin and padding for better
# visuals (and to better tell the active window)
window_margin_width 2
window_padding_width 4

# Hide the title bar
# NB: gnome allows to move any window by super+click and drag
hide_window_decorations yes

# set mouse_hide_wait to any <0 value to make the cursor disappear when typing
mouse_hide_wait -1.0

# #: notify the end of long (20s here) commands if unfocussed or invisible
# notify_on_cmd_finish unfocused 20

# inactive_border_color yellow
active_border_color yellow

# draw_window_borders_for_single_window yes

# tab_powerline_style round

tab_bar_edge bottom
tab_bar_style separator
tab_separator " "

# tab_bar_style powerline
# tab_powerline_style slanted

tab_bar_min_tabs 9999

# tab_title_template " {index} {title} "
tab_title_template " {index} "

# BEGIN_KITTY_THEME
# Gruvbox Dark
include current-theme.conf
# END_KITTY_THEME

# active_tab_background #ebdbb2
# active_tab_background #689d6a
# active_tab_background #458588
# active_tab_background #d79921
# active_tab_background #ebdbb2
active_tab_background #665c54
# active_tab_foreground black
inactive_tab_background #282828
active_tab_foreground #ebdbb2
inactive_tab_foreground #ebdbb2

# nice cursor trail for rapid movements
cursor_trail 5
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
